### ISSUE TITLE
Can you add two-layer authentication examples?

### ISSUE THREAD

**Issue by renomureza** [justincy/nextjs-auth#11]
Hi Justin,
I found this on dev.to, not many people have discussed this and it really helps me a beginner.

Your example worked fine.

I have several separate layouts,
1. LayoutApp => `withAuth(LayoutApp)`
2. LayoutAuth => `withoutAuth(LayoutAuth)`

Can you add an example of two-layer authentication, before the user is redirected to the main application:

1. Login with email and password.
2. Call it the second verification, this page is under the LayoutApp.

Thank you in advance,

**Comment by justincy** [comment]
@renomureza Could you clarify what you mean by two-layer authentication? The only thing I can think of is enforcing both auth and permissions. For example, I have an app where I have to check whether a user has an active subscription. Is that what you mean?

**Comment by renomureza** [comment]
@justincy  yes that's exactly right,

Users with an expired subscription cannot access the application. However, he can still log in and access the profile/account page, let's just say that the page uses LayoutAccount.

**Comment by justincy** [comment]
@renomureza HOCs can be wrapped so you'd do something like this: `withAuth(withSubscription(LayoutApp))`. `withSubscription()` would be setup similar to `withAuth` in that it'd have to create a wrapper component, define `getInitialProps`, and call the page component's `getInitialProps` (if it exists).

Does that make sense?

**Comment by renomureza** [comment]
@justincy  thanks, it worked fine.
