### ISSUE TITLE
Passed User Info along with Session, How to use in Pages ?

### ISSUE THREAD

**Issue by ctrljs** [justincy/nextjs-auth#2]
```
 let obj = { user: 'Hamrosh', id: 3 };
  res.setHeader(
    'Set-Cookie',
    [
      `session=1;  Max-Age=86400; SameSite=Strict; HttpOnly; Path=/`,
      ` myuser=${JSON.stringify(
        obj
      )}; Max-Age=86400; SameSite=Strict; HttpOnly; Path=/`,
    ]
  );

```
I added a user information object to the cookie for using it in pages. I can access it in _app props. 
```
  if (request) {
    request.cookies = cookie.parse(request.headers.cookie || '');
    authenticated = !!request.cookies.session;
    logged_user = request.cookies.myuser;
  }
// then in props of _app
 const { Component, pageProps, authenticated, logged_user } = this.props;
```
I am using your ssr method code.

Can you suggest how can I access the logged_user now in my pages for actual use? I am not getting the correct way to access this in my pages.

**Comment by ctrljs** [comment]
```
 <AuthContext.Provider
      value={{
        isAuthenticated,
        setAuthenticated,
        log_user,
      }}
    >
```
I added the value to Context Provider

```
export function useIsAuthenticated() {
  const context = useAuth();
  return context.isAuthenticated;
}

export function loggedInUser() {
  const context = useAuth();
  return context.log_user;
}
```

and then I created loggedInUser() function simliar to  useIsAuthenticated()  and I am using it the pages, it is working,hope it is a ideal solution.

**Comment by justincy** [comment]
If it works then that's great. However, I probably wouldn't send the user info in a cookie. I'd probably send it in the response body and then pull it out of the response client-side and put it into the context.

**Comment by ctrljs** [comment]
` res.status(200).send(data.signed_in_user);`

in login page after successful response 
```

 setAuthenticated(true);
      setLoggedUser(data);

```

I too put it into response body and then into context, but when I am using the context in pages, at initial loads from server, I am getting undefined error. Context will be available on client side only?? How to get use the user info properly?

**Comment by justincy** [comment]
@ctrljs I recommend getting help with this in Next or React communities.
