### ISSUE TITLE
props is undefined when using Router.push

### ISSUE THREAD

**Issue by shcohen2002** [justincy/nextjs-auth#3]
Hi, 
I am using the static project with Next.js.
Here is my "package.json" file:

```
{
  "name": "user-auth-http-only-cookie",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
  },
  "dependencies": {
    "@material-ui/core": "^4.9.12",
    "@material-ui/icons": "^4.9.1",
    "cookie": "^0.4.1",
    "crypto-js": "^4.0.0",
    "next": "9.4.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-export-excel": "^0.5.3",
    "xlsx": "^0.16.1"
  }
}
```

My "server.js" file is:

```
const { createServer } = require('https');
const { parse } = require('url');
const next = require('next');
const fs = require('fs');

const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();

const httpsOptions = {
  key: fs.readFileSync('./certs/server.key'),
  cert: fs.readFileSync('./certs/server.cert')
};

app.prepare().then(() => {
  createServer(httpsOptions, (req, res) => {
    const parsedUrl = parse(req.url, true);
    handle(req, res, parsedUrl);

  }).listen(3000, err => {
    if (err) throw err;
    console.log('> Ready on https://localhost:3000');
  });
});
``` 

I have added 2 files A and B which have a functional component in each one of them.
functional component A calls functional component B on a click of a button.
In the button method there is a Router.push command that pass parameters into the URI to be used in the functional component B props.
Unfortunately i am keep getting an undefined  props object in functional component B.
Here is part of the code:

```
import Router from 'next/router'
export default function A(props){

const handleButton = (event) => {
  Router.push({
      pathname: '/B',
      query: { projectId: someID,
              query: someQuery},
    })
}
return (
...
)
}

export default function B(props){
 console.log(props)
return (
...
)
}
```

I have also tried this way with no success:
```
import Router from 'next/router'
import withAuth from '../hocs/withAuth';
export default withAuth(function A(props){

const handleButton = (event) => {
  Router.push({
      pathname: '/B',
      query: { projectId: someID,
              query: someQuery},
    })
}
return (
...
)
})

import withAuth from '../hocs/withAuth';

export default withAuth(function B(props){
 console.log(props)
return (
...
)
})
```

Can you please tell me what am i missing, i guess something with using the HOC correctly? 
I tried using it as in Profile file though with no success of getting the URI parameters in props.
Thanks

**Comment by justincy** [comment]
@shcohen2002 What props are you expecting? It doesn't look to me like the component should be receiving any props.

**Comment by shcohen2002** [comment]
Hi @justincy ,
If i am not using HOC and i call the following command:
`Router.push({
      pathname: '/B',
      query: { projectId: someID,
              query: someQuery},
    })`

Then B component page will be called and the props will be populated with the query i have passed from the command.
If there is another way to open the B component page and pass the query data into the props i would be happy to know but i didn't find a way.
Thanks

**Comment by justincy** [comment]
@shcohen2002 That information is available from the router which can be accessed via the [useRouter()](https://nextjs.org/docs/api-reference/next/router#userouter) hook.
