### ISSUE TITLE
Redirect user to the protected page after successfully login

### ISSUE THREAD

**Issue by kirkegaard** [justincy/nextjs-auth#5]
These hocs are awesome and exactly what i was looking for. I've added some minor tweaks that'll redirect the user to the protected page after authenticating. Right now im using a cookie like this:

```javascript
export default function withAuthRedirect({
  WrappedComponent,
  LoadingComponent = Loading,
  expectedAuth,
  location,
  useTargetUri,
}) {
  const WithAuthRedirectWrapper = (props) => {
    const cookies = parseCookies();
    const router = useRouter();
    const { isLoading, isAuthenticated } = useAuth();

    if (useTargetUri && expectedAuth && !isAuthenticated) {
      setCookie(null, "targetUri", router.asPath, {
        maxAge: 30 * 60,
      });
    }

    if (isLoading) {
      return <LoadingComponent />;
    }

    if (process.browser && expectedAuth !== isAuthenticated) {
      if (isAuthenticated && cookies.targetUri) {
        destroyCookie(null, "targetUri");
        router.push(cookies.targetUri);
      } else {
        router.push(location);
      }
      return <></>;
    }
    return <WrappedComponent {...props} />;
  };
  return WithAuthRedirectWrapper;
}
```
This works but has another defect. If you click on a protected page -> then public page -> then login, ill be redirected to the protected page. I would expect to be redirected to the public page, or whatever location ive set in my `withoutAuth(login, {location here})` but since we dont destroy the cookie if you decide to move on after the protected page ill still be there.

What i really want was to have withAuth add a urlparam to the location variable, like `http://foo:3000/login?targetUri={my initial url request that required me to login}`. Ive tried a few things but without any success. Do you have an idea of how i could implement a thing like this or point me in the right direction? :)

**Comment by justincy** [comment]
You can call [useRouter()](https://nextjs.org/docs/api-reference/next/router#userouter) to get access to the Next.js router and lookup the current path. 

```js
const { asPath } = useRouter();
```

Then when you do the redirect you can append that as a query param.

```js
router.push({
    pathname: location,
    query: { targetUri: asPath },
});
```

Something like that.

**Comment by kirkegaard** [comment]
You're absolutely right! That'll work perfectly. Thank you so much! Cant believe i was stuck on this for so long :D

This is what i ended up doing

```javascript
export default function withAuthRedirect({
  WrappedComponent,
  LoadingComponent = Loading,
  expectedAuth,
  location,
}) {
  const WithAuthRedirectWrapper = (props) => {
    const router = useRouter();
    const { isLoading, isAuthenticated } = useAuth();

    if (isLoading) {
      return <LoadingComponent />;
    }

    if (process.browser && expectedAuth !== isAuthenticated) {
      const { targetUri } = router.query;
      if (targetUri) {
        router.push(targetUri);
      } else {
        router.push({
          pathname: location,
          query: { targetUri: router.asPath },
        });
      }
      return <></>;
    }
    return <WrappedComponent {...props} />;
  };
  return WithAuthRedirectWrapper;
}
```
