### ISSUE TITLE
Adapt for use with refresh token

### ISSUE THREAD

**Issue by GerwarKi** [justincy/nextjs-auth#7]
how to do when authentication API asks for a username and password, and returns a HTTPOnly cookie (which is a JWT with an expiration date) also the basic user's information.
The idea is to have a timer that removes the cookie when the expiration date indicates it.
Look at the following example, the `authentication.service.ts` file is the one I want to adapt.
https://jasonwatmore.com/post/2020/07/25/angular-10-jwt-authentication-with-refresh-tokens#authentication-service-ts
look at the `startRefreshTokenTimer()`
I don't know where in the project to adapt that code

**Comment by justincy** [comment]
I would probably add that functionality to the [Auth provider](https://github.com/justincy/nextjs-client-auth-architectures/blob/master/ssr/src/providers/Auth.js). You would need to wrap `setAuthenticated()` in a function where you start and stop the timer. Or replace `setAuthenticated()` with `login()` and `logout()`; you'd start the timer inside of `login()` and stop it in `logout()`.

Does that make sense?
