### ISSUE TITLE
(SSR)Warning: WithConditionalRedirectWrapper returned an empty object from `getInitialProps`

### ISSUE THREAD

**Issue by GerwarKi** [justincy/nextjs-auth#8]
warning is displayed when a component that uses the wrapper is mounted. in `ssr` and `ssr-ts`

_WithConditionalRedirectWrapper returned an empty object from `getInitialProps`. This de-optimizes and prevents automatic static optimization. https://err.sh/zeit/next.js/empty-object-getInitialProps__

**Comment by justincy** [comment]
> If you meant to do this and understand the consequences you can ignore this message as it is only shown in development.

It's intentional. `getInitialProps` is used to determine whether the user is authenticated. It's required for looking at the cookies.
