### ISSUE TITLE
You can not use getInitialProps with getServerSideProps. Please remove getInitialProps

### ISSUE THREAD

**Issue by skyrocketeer** [justincy/nextjs-auth#9]
I was doing exactly what the example for ssr ts says.
But in one of my protected routes, it needs to call api with get serversideprops to populate the page content and next js is not happy with me.
Do you have a workaround for this

**Comment by justincy** [comment]
`getInitialProps` and `getServerSideProps` are not compatible. The examples in this repo were created before `getServerSideProps` were created. The SSR examples ought to be updated to use `getServerSideProps`. I hope to do that some day.

**Comment by justincy** [comment]
#10

**Comment by skyrocketeer** [comment]
> #10

Great, hope to expect the release of this fix real soon
